  app:
    build: .
    dockerfile: ./deploy/app/Dockerfile
    environment:
     - ELASTICSEARCH_URL=http://localhost:9200
    links:
     - elasticsearch
    ports:
     - "80:80"


  elasticsearch:
    build: .
    dockerfile: ./deploy/elasticsearch/Dockerfile
    ports:
     - "9200:9200"
     - "9300:9300"

  init:
    build: .
    dockerfile: ./deploy/init/Dockerfile
    links:
      - elasticsearch
